import type { SpecimenVariant } from '../../types.js';

export const taskReplicationVariant = {
  id: 'task-replication',
  status: 'focus',
  frames: [
    [
      '',
      '      [ monitor ]',
      '      > TODO: 1 🐣',
      '',
      '[ MINOR OBLIGATION DETECTED ]',
      '',
      '                /\\__/\\',
      '               ( o.o )',
      '                > ^ <',
      '                /| |\\',
      '               ( | | )~~~~/',
    ],
    [
      '',
      '      [ monitor ]',
      '      > TODO: 1',
      '      > if (bug) hiss();_',
      '[ TASK ENGAGEMENT CONFIRMED ]',
      '',
      '                /\\__/\\',
      '               ( ■.■ )',
      '                > ^ <',
      '              __/| |\\_',
      '             (   | |   )~~~~_',
    ],
    [
      '',
      '      [ monitor ]',
      '      > TODO: 1',
      '      > meowc main.cat',
      '',
      '',
      '                /\\__/\\',
      '    *tap tap*  ( ■.■ )',
      '                > ^ <',
      '               _/| |\\__',
      '             (   | |   )~~~~/',
    ],
    [
      '',
      '      [ monitor ]',
      '      > TODO: 1',
      '      > purr test_',
      '',
      '',
      '                /\\__/\\',
      '               ( ■.■ )',
      '                > ^ <',
      '              __/| |\\_',
      '             (   | |   )~~~~_',
    ],
    [
      '',
      '      [ monitor ]',
      '      > TODO: 0',
      '      ✓ tests passed',
      '[ REWARD CHEMISTRY ELEVATED ]',
      '',
      '                /\\__/\\',
      '               ( ^.^ )',
      '                > ^ <',
      '               _/| |\\',
      '              (  | | )~~~~~',
    ],
    [
      '',
      '      [ monitor ]',
      '      > TODO: 0',
      '      > _',
      '',
      '',
      '                /\\__/\\',
      '               ( ~.~ )    +1 serotonin',
      '                > ^ <',
      '               _/| |\\',
      '              (  | | )~~~~^',
    ],
    [
      '',
      '      [ monitor ]',
      '      > TODO: 0',
      '      >',
      '',
      '',
      '                /\\__/\\',
      '               ( ^.^ )',
      '                > ^ <',
      '               _/| |\\',
      '              (  | | )~~~~~',
    ],
    [
      '',
      '      [ monitor ]',
      '      > TODO: 3',
      '      > _',
      '[ SPONTANEOUS TASK BUDDING DETECTED ]',
      '',
      '                /\\__/\\    /',
      '       + + +   ( o.o )   /',
      '                > ^ <   /',
      '               _/| |\\  /',
      '              (  | | )/',
    ],
    [
      '',
      '      [ monitor ]',
      '      > TODO: 27',
      '      >',
      '[ UNCONTROLLED TASK REPLICATION ]',
      '',
      '                /\\__/\\',
      '               ( -.- )',
      '                > ^ <',
      '          +    _/| |\\',
      '        + + + (  | | )~~~~\\_',
      '      + + + + + + +',
    ],
    [
      '',
      '      [ monitor ]',
      '      > TODO: 27',
      '      > _',
      '',
      '',
      '                /\\__/\\',
      '               ( -.- )   serotonin revoked',
      '                > ^ <',
      '       +       _/| |\\',
      '         + +  (  | | )~~~~_/',
      '    + + + + + + +',
    ],
    [
      '',
      '      [ monitor ]',
      '      > TODO: 27',
      '      >',
      '',
      '',
      '                /\\__/\\',
      '               ( -.- )',
      '                > ^ <',
      '          +    _/| |\\',
      '        + + + (  | | )~~~~\\_',
      '      + + + + + + +',
    ],
    [
      '',
      '      [ monitor ]',
      '      > ~~TODO: 27~~',
      '      > paw commit -m "temporary fix"_',
      '[ CONTAINMENT DECLARED SUCCESSFUL ]',
      '',
      '                /\\__/\\',
      '               ( ^.^ )',
      '                > ^ <',
      '                /| |\\',
      '               ( | | )~~~~~',
    ],
    [
      '',
      '      [ monitor ]',
      '      > ~~TODO: 27~~',
      '      > paw commit -m "temporary fix"',
      '',
      '',
      '                /\\__/\\',
      '               ( -.- )   technical debt',
      '                > ^ <       sleeping',
      '                /| |\\',
      '               ( | | )~~~~^',
    ],
    [
      '',
      '      [ monitor ]',
      '      > ~~TODO: 27~~',
      '      > paw commit -m "temporary fix"_',
      '',
      '',
      '                /\\__/\\',
      '               ( ^.^ )',
      '                > ^ <',
      '                /| |\\',
      '               ( | | )~~~~~',
    ],
  ],
  narration: [],
  frameX: 45,
  note: [
    'Task completion produced a brief reward response.',
    'The effect did not survive subsequent replication.',
  ],
  observations: [
    ['task count', 'contained'],
    ['system stability', 'provisional'],
    ['fix permanence', 'questionable'],
    ['technical debt', 'dormant'],
    ['subject confidence', 'restored'],
  ],
} satisfies SpecimenVariant;
