import type { SpecimenVariant } from '../../types.js';

export const signalLossVariant = {
  id: 'signal-loss',
  status: 'offline',
  frames: [
    [
      '',
      '      [ monitor ]',
      '      > paw status_',
      '',
      '[ RESPONSE LATENCY INCREASING ]',
      '',
      '                /\\__/\\',
      '               ( -.- )',
      '                > ^ <',
      '                /| |\\',
      '               ( | | )~~~~~',
    ],
    [
      '',
      '      [ monitor ]',
      '      > paw status',
      '',
      '',
      '',
      '                /\\__/\\',
      'drowsiness +1  ( ~.~ )',
      '                > ^ <',
      '                /| |\\',
      '               ( | | )~~~~^',
    ],
    [
      '',
      '      [ monitor ]',
      '      > _',
      '',
      '',
      '',
      '                /\\__/\\',
      '               ( -.- )',
      '                > ^ <',
      '                /| |\\',
      '               ( | | )~~~~~',
    ],
    [
      '',
      '      [ monitor ]',
      '      >',
      '',
      '[ SUBJECT SIGNAL DEGRADING ]',
      '',
      '',
      '                /\\__/\\',
      '               ( -.- )',
      '                > ^ <',
      '               ( | | )~~~~/',
    ],
    [
      '',
      '      [ monitor ]',
      '      > _',
      '',
      '',
      '',
      '',
      '',
      '                /\\__/\\',
      '               ( -.- )',
      '               ( | | )~~~~/',
    ],
    [
      '',
      '      [ monitor ]',
      '      >',
      '',
      '',
      '',
      '',
      '',
      '',
      '                  /\\',
      '               ~~~~/',
    ],
    [
      '',
      '      [ monitor ]',
      '      > _',
      '',
      '[ VISUAL CONTACT LOST ]',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '      [ monitor ]',
      '      >',
      '',
      '',
      '',
      '',
      '',
      '  (zzz detected off-camera)',
      '',
      '',
    ],
    [
      '',
      '      [ monitor ]',
      '      > _',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '      [ monitor ]',
      '      >',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '      [ monitor ]',
      '      > _',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '      [ monitor ]',
      '      >',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
  ],
  narration: ['ACTIVITY NOT DETECTED', 'SPECIMEN UNRESPONSIVE'],
  narrationFrameIndexes: [8, 9, 10, 11],
  note: [
    'The subject resolved the activity problem',
    'by creating a tracking problem.',
  ],
  observations: [
    ['productive demand', 'neutralized'],
    ['tracking burden', 'introduced'],
    ['subject accountability', 'unavailable'],
    ['location confidence', 'speculative'],
    ['problem inventory', 'conserved'],
  ],
} satisfies SpecimenVariant;
